### ISSUE TITLE
DateTime incorrectly rounded off during serialization and deserialization

### ISSUE THREAD

**Issue by janny93** [AdrianStrugala/AvroConvert#108]
**What is the bug?**
Serialization, or deserialization, incorrectly rounds off DateTime milliseconds / Z component.
![image](https://user-images.githubusercontent.com/124273385/236480004-3ccf23c9-0ab1-4383-bf1f-d4a0742edae6.png)

**How to reproduce?**
AvroConvert package version: 3.3.4

Example code:
```
public class SomeModel
{
    public DateTime? SomeTime { get; set; }
    public DateTime AnotherTime { get; set; }
}

[Fact]
public void DemonstrateError()
{
    var model = new SomeModel();
    model.SomeTime = DateTime.Parse("2023-05-05T13:56:28.0842841Z");
    model.AnotherTime = DateTime.Parse("2020-03-19T17:16:38.0840130Z");

    // Serialize
    var serializedModel = AvroConvert.Serialize(model);

    // Deserialize
    var deserializedModel = AvroConvert.Deserialize<SomeModel>(serializedModel);

    // Verify
    deserializedModel.Should().BeEquivalentTo(model);
}
```

*What is the Avro schema?*
I used `AvroConvert.GetSchema(serializedModel);` to get the schema below.

```
{"name":"SomeModel","namespace":"<redacted>","type":"record","fields":[{"name":"SomeTime","type":["null",{"type":"long","logicalType":"timestamp-millis"}]},{"name":"AnotherTime","type":{"type":"long","logicalType":"timestamp-millis"}}]}
```

*What is the Avro data? Fill up the section or provide a sample file*
NA

**What is the expected behavior?**
Expect to see the same DateTime value before and after serialization/deserialization.

**Comment by AdrianStrugala** [comment]
Hi @janny93 ,
Sorry for the late answer. It turned out to surprisingly complex topic. I've managed to increase the precision to microseconds -[branch](https://github.com/AdrianStrugala/AvroConvert/tree/issue/108/increase-precision-of-date-time).
And this is the best I can do according to the Avro [docs](https://avro.apache.org/docs/1.11.0/spec.html#Timestamp+%28microsecond+precision%29). So the ticks precision and timezone info is still lost.

Not sure if you are still into this topic, but is that sufficient for you? I have an idea how to progress with the topic, but it requires even more time.

Adrian

**Comment by janny93** [comment]
Hi, thanks for the effort into this issue and sorry for the late reply here, didnt catch it amongst my emails and recent holiday.

I remember when I had the issue I looked into a workaround with using another avro type (probably string) to store the ticks and when initializing the datetime during parsing I would use the stored ticks, thus preserving everything. Though that might not be following avro guidelines. Didnt look into it after that, as we ended up using another approach.

I might have a look later on in my spare time since as long as we got a unit test for this scenario it could be interesting to give it a go.

Best Regards,
Jan Inge
