### ISSUE TITLE
Logical Types

### ISSUE THREAD

**Issue by ecarlson94** [AdrianStrugala/AvroConvert#29]
What do you guys think of having the `long` write operation produce a [logical type](https://avro.apache.org/docs/current/spec.html#Logical+Types) for DateTime as well? Automatically (like `timestamp-millis`) and/or explicitly through annotations?

**Comment by AdrianStrugala** [comment]
Logical Types would be definitely the next step in the evolution of AvroConvert. I just started an investigation, how it should be implemented correctly.
If you have an idea, PRs are more than welcome :)

**Comment by smitty-codes** [comment]
I'm running into the same thing - I used EF core power tools convert a database table into a POCO (77 properties). Then I converted this POCO into an Avro schema using AvroConvert but most of my data types are wrong in the avro schema (DateTime, Decimal? etc output as strings).

I have a ton of POCOs than need converted to avro schemas so I did not want to hand fix a bunch of schemas and I haven't found a good C# solution via googling.

I ended up trying a different angle: generate the Avro schema from the database first, then from the avro schema generate the POCO using avrogen tool. Unfortunately the fastest way to do this is to use NetBeans/Java since there is a [database to avro schema library](https://github.com/artur-tamazian/avro-schema-generator):

1. Install [NetBeans](https://netbeans.apache.org/)
2. Open NetBeans and create a new Maven project
3. Open the pom.xml file and add a reference to [artur-tamazian/avro-schema-generator](https://github.com/artur-tamazian/avro-schema-generator#maven-dependency)
4. Add a new java class and the code below (in my case I had to download the [sql server JDBC driver](https://docs.microsoft.com/en-us/sql/connect/jdbc/microsoft-jdbc-driver-for-sql-server?view=sql-server-ver15) and [setup windows auth integrated security](https://docs.microsoft.com/en-us/sql/connect/jdbc/building-the-connection-url?view=sql-server-ver15#Connectingintegrated))
5. Run the project in NetBeans and it should connect to your db and generate a bunch of avro schemas for each table.
6. After the schema is created, install [Apache.Avro.Tools](https://www.nuget.org/packages/Apache.Avro.Tools/) and use the command line "avrogen" tool to generate POCOs from the avro schema.

```
public static void main(String[] arguments) {
	String sqlConnStr = "jdbc:sqlserver://127.0.0.1\\SQL2019;databaseName=AvroGen";
	DbSchemaExtractor schemaExtractor = new DbSchemaExtractor(sqlConnStr, "sa", "mypassword");
	AvroConfig avroConfig = new AvroConfig("some.namespace")
		.setUnknownTypeResolver(type -> "string");
	List<AvroSchema> schemas = schemaExtractor.getAll(avroConfig);
	for (AvroSchema schema : schemas) {
		String schemaJson = SchemaGenerator.generate(schema);
		System.out.println(schemaJson);
	}
}
```

I know this is totally not elegant but its actually cleaner and faster than hand fixing many avro schema files at least if your POCOs are very similar to database tables.

**Comment by AdrianStrugala** [comment]
Hi,
Support for Logical Types is under implementation. You can find it here: [https://github.com/AdrianStrugala/AvroConvert/tree/Add-support-for-Logical-Types](https://github.com/AdrianStrugala/AvroConvert/tree/Add-support-for-Logical-Types)

It's almost ready, but I have one doubt. Maybe you can help me @ecarlson94  @smitty-codes 

Consider Avro Decimal, which requires Scale property. This property is hardcoded in the schema, but the scale of .NET values may vary. How, in your opinion, the serialization should behave in the following example:

Scale = 2

Serialized values:
99.99 -> 99.99
9.99 -> 9.99
but
9 -> ?
99.9 ->?
99.999 -> ?

The serializer should throw an exception? Or try to round the value?
I want to keep users models technology agnostic, so I don't want to force them to set up the required Scale attribute. What should be the default Scale then? 2 (as for prices) or 14 (which is C# scale for decimals)?

**Comment by smitty-codes** [comment]
In my situation I work with accounting systems so those tend to only need 2 decimal places because of money/currency fields. I could see though dealing with latitude and longitude and needing more decimal places.

I think an overload with additional parameters to define these thing would be better but defaulting to 2 could be fine.

I feel the library I mentioned before the author ran across the same thinking and took a fluent approach to defining all these settings https://github.com/artur-tamazian/avro-schema-generator#more-complex-example

**Comment by ecarlson94** [comment]
Could we do this?

Scale = 14

Serialized values:
```
99.99 -> 99.99000000000000
99.999 -> 99.99900000000000
```

and then

Deserialized values:
99.99000000000000 -> 99.99
99.99900000000000 -> 99.999

This way, you would have to worry about rounding at all and the scale will work regardless of the C# value.

**Comment by AdrianStrugala** [comment]
There is another problem there:
Decimal can contain only up to 29 digits. If I'm trying to convert small values, everything is fine. But in a case:

-123456789123456789.56 -> -123456789123456789.56000000000 
(cut's off 3 trailing zeros and I'm unable to determine the real precision during deserialization)

**Comment by ecarlson94** [comment]
Well, shucks! It was worth a try. In that case, I think @smitty-codes default scale of 2 with an overload idea is the best. Maybe the overload could be an attribute.

I think we should also couple it with a rounding solution. Where:

Scale = 2

Serialized values:
```
99.999 => 100
99.989 => 99.99
99.945 => 99.95
99.944 => 99.94
99.9 => 99.90
```

Regarding the last example, we could still run into the the problem you mentioned. We might be forced to stringify the value before serialization and "manually" add trailing zeroes rather than relying on a black box serialization. Is there a way to create a custom serializer for that type? 

Hopefully I made sense. It's been a minute since I have looked at the code. Feel free to probe for more details if I wasn't clear.

**Comment by AdrianStrugala** [comment]
Hi,

The Logical Types are now fully supported. It was breaking change, that's why it can be found in v.3.0.0 of the package.
@ecarlson94  @smitty-codes  could you play with it to confirm, that it works as expected?

The decimals are handed in a way, that always has a Scale of 14. I managed to find a workaround for .NET decimals.

Regards,
Adrian
